name: brentnoble
favicon: null
layout_spectrum: 0.7457289623562247
typography_spectrum: 0.6102859720122069
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.46825246582739055
  lightness: 0.6515718267764896
  saturation: 0.855718073900789
  rhythmicContrast: 0.6826671531889588
purpose: []
